[package]
name = "egraph"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
derive-debug = "0.1.2"
derive_more = { version = "2.0.1", features = ["full"] }
either = "1.15.0"
hashbrown = "0.16.0"
stable-vec = "0.4.1"
